START TRANSACTION;

CREATE TABLE "Banners" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Banners" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_Banners_Deleted" ON "Banners" ("Deleted");

CREATE UNIQUE INDEX "IX_Banners_Key" ON "Banners" ("Key");

CREATE INDEX "IX_Banners_Name" ON "Banners" ("Name");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220317041534_CreateBannerTable', '6.0.3');

COMMIT;
