START TRANSACTION;

CREATE TABLE "ReceiptLines" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ArticleId" integer NOT NULL,
    "ArticleName" character varying(100) NOT NULL,
    "BannerId" integer NULL,
    "BannerName" character varying(100) NULL,
    "Category" character varying(100) NOT NULL,
    "DepartmentId" integer NULL,
    "DepartmentName" character varying(100) NULL,
    "DepartmentNumber" character varying(32) NULL,
    "Flags" character varying(10) NULL,
    "Gtin" bigint NULL,
    "IssuedAt" timestamp with time zone NOT NULL,
    "ItemId" integer NOT NULL,
    "Price" money NOT NULL,
    "ProductId" integer NOT NULL,
    "ProductLabel" character varying(100) NULL,
    "Quantity" double precision NOT NULL,
    "ReceiptId" integer NOT NULL,
    "ReceiptNumber" character varying(32) NULL,
    "Sku" character varying(32) NULL,
    "StoreId" integer NOT NULL,
    "StoreName" character varying(100) NOT NULL,
    "StoreNumber" character varying(32) NULL,
    "UnitPrice" money NOT NULL,
    "UnitType" character varying(4) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_ReceiptLines" PRIMARY KEY ("Id")
);

CREATE TABLE "Receipts" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "IssuedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "Number" character varying(32) NULL,
    "StoreId" integer NOT NULL,
    "SubTotal" money NOT NULL,
    "Total" money NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Receipts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Receipts_Stores_StoreId" FOREIGN KEY ("StoreId") REFERENCES "Stores" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReceiptItems" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Key" uuid NOT NULL,
    "Price" money NOT NULL,
    "ProductId" integer NOT NULL,
    "Quantity" double precision NULL,
    "ReceiptId" integer NOT NULL,
    "UnitPrice" money NOT NULL,
    CONSTRAINT "PK_ReceiptItems" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ReceiptItems_Products_ProductId" FOREIGN KEY ("ProductId") REFERENCES "Products" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ReceiptItems_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE
);

CREATE TABLE "ReceiptTaxes" (
    "Code" character varying(4) NOT NULL,
    "ReceiptId" integer NOT NULL,
    "Amount" money NOT NULL,
    "Rate" double precision NOT NULL,
    "TaxableAmount" money NOT NULL,
    CONSTRAINT "PK_ReceiptTaxes" PRIMARY KEY ("ReceiptId", "Code"),
    CONSTRAINT "FK_ReceiptTaxes_Receipts_ReceiptId" FOREIGN KEY ("ReceiptId") REFERENCES "Receipts" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_ReceiptItems_Key" ON "ReceiptItems" ("Key");

CREATE INDEX "IX_ReceiptItems_ProductId" ON "ReceiptItems" ("ProductId");

CREATE INDEX "IX_ReceiptItems_ReceiptId" ON "ReceiptItems" ("ReceiptId");

CREATE INDEX "IX_ReceiptLines_Deleted" ON "ReceiptLines" ("Deleted");

CREATE UNIQUE INDEX "IX_ReceiptLines_ItemId" ON "ReceiptLines" ("ItemId");

CREATE UNIQUE INDEX "IX_ReceiptLines_Key" ON "ReceiptLines" ("Key");

CREATE INDEX "IX_ReceiptLines_ReceiptId" ON "ReceiptLines" ("ReceiptId");

CREATE INDEX "IX_Receipts_Deleted" ON "Receipts" ("Deleted");

CREATE UNIQUE INDEX "IX_Receipts_Key" ON "Receipts" ("Key");

CREATE INDEX "IX_Receipts_Number" ON "Receipts" ("Number");

CREATE INDEX "IX_Receipts_StoreId" ON "Receipts" ("StoreId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220317173234_CreateReceiptTables', '6.0.3');

COMMIT;
