START TRANSACTION;

CREATE TABLE "Stores" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "BannerId" integer NULL,
    "Description" text NULL,
    "Name" character varying(100) NOT NULL,
    "Number" character varying(32) NULL,
    "Address" character varying(100) NULL,
    "City" character varying(100) NULL,
    "Country" character(2) NULL,
    "Phone" character varying(40) NULL,
    "PostalCode" character varying(10) NULL,
    "State" character(2) NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (now()),
    "CreatedById" uuid NOT NULL,
    "Deleted" boolean NOT NULL DEFAULT FALSE,
    "DeletedAt" timestamp with time zone NULL,
    "DeletedById" uuid NULL,
    "Key" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "UpdatedAt" timestamp with time zone NULL,
    "UpdatedById" uuid NULL,
    "Version" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_Stores" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stores_Banners_BannerId" FOREIGN KEY ("BannerId") REFERENCES "Banners" ("Id")
);

CREATE INDEX "IX_Stores_BannerId" ON "Stores" ("BannerId");

CREATE INDEX "IX_Stores_Deleted" ON "Stores" ("Deleted");

CREATE UNIQUE INDEX "IX_Stores_Key" ON "Stores" ("Key");

CREATE INDEX "IX_Stores_Name" ON "Stores" ("Name");

CREATE INDEX "IX_Stores_Number" ON "Stores" ("Number");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20220317143336_CreateStoreTable', '6.0.3');

COMMIT;
