name: Linux Container Node Workflow

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: francispion.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t francispion.azurecr.io/faktur-api:${{ github.sha }} api/src/Faktur.Web/Dockerfile
          docker push francispion.azurecr.io/faktur-api:${{ github.sha }}
