name: Publish Docker backend image to Docker Hub

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  publish:
    name: Publish Docker backend image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: fpion/faktur-backend

      - name: Build and push Docker backend image
        uses: docker/build-push-action@v5
        with:
          file: backend/src/Faktur/Dockerfile
          context: ./backend
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
