name: Build Faktur Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"
  pull_request:
    branches:
      - main
    paths:
      - "frontend/**"
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend

jobs:
  build:
    name: Build Faktur Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        run: npm clean-install

      - name: Build for Production
        run: npm run build

      - name: Run Tests & Coverage
        run: npm run test
